### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by guillemv** [de-code/python-classdojo-archive#60]
Good morning,
I've tried to execute the script but I receive the following error:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/python-classdojo-archive/dojo_archive/cli.py", line 81, in <module>
    main()
  File "/python-classdojo-archive/dojo_archive/cli.py", line 73, in main
    run(config)
  File "/python-classdojo-archive/dojo_archive/cli.py", line 50, in run
    client.login()
  File "/python-classdojo-archive/dojo_archive/client.py", line 60, in login
    response = self.on_response(self.session.post(self.config.login_url, json={
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python-classdojo-archive/venv/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python-classdojo-archive/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python-classdojo-archive/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python-classdojo-archive/venv/lib/python3.12/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='home.classdojo.com', port=443): Max retries exceeded with url: /api/session (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))
make: *** [run] Error 1

**Comment by de-code** [comment]
Thank you for raising the issue. I can't reproduce it.

I could suggest to try a lower Python version, e.g. Python 3.9.
Although I tried running it with Python 3.12 as well and it was working.

The update on a [stackoverflow post](https://stackoverflow.com/questions/55680224/how-to-fix-requests-exceptions-sslerror) seem to suggest that it could be caused by configuration in `/etc/ssl`.

**Comment by de-code** [comment]
Closing due to inactivity
